spring.application.name=social-media-social-service
server.port=8083

# Database configuration for SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SocialMediaDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=abc
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

services.media-service-url=${MEDIA_SERVICE_URL:http://localhost:8084}