spring.application.name=user-service-social-media

server.port=8082

# Database configuration
spring.mongodb.uri=${MONGO_USER_URI:mongodb://localhost:27017/socialmediauserdb}

# Kafka configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=user-service-group
spring.kafka.producer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.topic.create-profile=auth.user.created