server.port=8080

spring.application.name=social-media-api-gateway
spring.mongodb.uri=mongodb://localhost:27017/socialmediaauthdb

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=${services.auth-service-url:http://localhost:8081}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=${services.user-service-url:http://localhost:8082}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[2].id=social-service
spring.cloud.gateway.server.webflux.routes[2].uri=${services.social-service-url:http://localhost:8083}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/social/**

spring.cloud.gateway.server.webflux.routes[3].id=media-service
spring.cloud.gateway.server.webflux.routes[3].uri=${services.media-service-url:http://localhost:8084}
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/media/**

spring.cloud.gateway.server.webflux.routes[4].id=chat-service
spring.cloud.gateway.server.webflux.routes[4].uri=${services.chat-service-url:http://localhost:8085}
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/chat/**

spring.cloud.gateway.server.webflux.routes[5].id=notification-service
spring.cloud.gateway.server.webflux.routes[5].uri=${services.notification-service-url:http://localhost:8086}
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/notifications/**



management.endpoints.web.exposure.include=health,info,metrics

jwt.secret=${JWT_SECRET:c29jaWFsLW1lZGlhLWF1dGgtc2VydmljZS1zZWNyZXQ=}

gateway.auth.public-paths[0]=/api/auth/**
gateway.auth.public-paths[1]=/actuator/health
gateway.auth.public-paths[2]=/actuator/info

gateway.auth.revocation-check.enabled=true
gateway.auth.revocation-check.mode=mongo
gateway.auth.revocation-check.token-type=ACCESS
gateway.auth.revocation-check.auth-service.introspection-url=${AUTH_INTROSPECTION_URL:http://localhost:8081/api/auth/introspect}
gateway.auth.revocation-check.auth-service.connect-timeout-ms=2000
gateway.auth.revocation-check.auth-service.read-timeout-ms=2000

services.auth-service-url=http://localhost:8081
services.user-service-url=http://localhost:8082
services.post-service-url=http://localhost:8083
services.media-service-url=http://localhost:8084
services.chat-service-url=http://localhost:8085
services.notification-service-url=http://localhost:8086
