spring.application.name=social-media-notification-service
server.port=8086

spring.mongodb.uri=mongodb://localhost:27017/socialmedianotificationdb

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest

notification.kafka.consumer-group=notification-service-group
notification.kafka.topics.social-events=social-notification-events
notification.kafka.topics.chat-events=chat-notification-events
notification.kafka.topics.dead-letter=notification-dead-letter
